language: node_js

sudo: required
dist: xenial

branches:
  only:
  - master
  - stable

node_js:
  - "node"

compiler:
  - gcc

cache:
  apt: true
  yarn: true
  directories:
    - opencv
    - protobuf
    - node_modules

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y build-essential dpkg-dev
  - sudo apt-get install -y cmake git libopenblas-dev libprotobuf-dev libssl-dev libgnutls28-dev libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y python-dev python-numpy libjpeg-dev libpng-dev libtiff-dev libjasper-dev
  - ./.travis.yml.sh

script:
  - yarn install --pure-lockfile
